### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#7]
In menu Add_Items menu upon clicking submit button I trigger except on line 291 & get the error "unknown error"

**Comment by DataWearsAHood** [comment]
Line 288 is blank - in the latest commit (from 7-Aug)
https://github.com/AIatMyCommand/Inventory_Profitability_Analyzer/blob/17f47b318c1877f8ae262216bdc487434b7416a8/Inventory_Profitability_Analyzer/Product_Line_Analyzer.py#L288

**Comment by AIatMyCommand** [comment]
Now it's line 63

**Comment by DataWearsAHood** [comment]
Still 2-day-old code: 
![image](https://user-images.githubusercontent.com/44448030/183756774-dddee4bb-d6cd-461e-8569-b52b846318c7.png)

This [version of] line 63?
https://github.com/AIatMyCommand/Inventory_Profitability_Analyzer/blob/17f47b318c1877f8ae262216bdc487434b7416a8/Inventory_Profitability_Analyzer/Product_Line_Analyzer.py#L63

**Comment by DataWearsAHood** [comment]
Indent 1 more time (so it only runs if there is an Exception _other_ than a `ValueError`): https://github.com/AIatMyCommand/Inventory_Profitability_Analyzer/blob/ce8ee4c969fedbad524ef32bde7a7d85cf664105/Inventory_Profitability_Analyzer/Product_Line_Analyzer.py#L63

Otherwise it will `raise` each time the `try/except` block runs.

**Comment by AIatMyCommand** [comment]
I just updated the line number because this is still happening

**Comment by DataWearsAHood** [comment]
You have `raise CustomError("Unknown Error")` in ~6 places - add a line# to each to figure out _which_ one is firing
